# Generated by Django 3.2.5 on 2021-07-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210731_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.IntegerField(null=True),
        ),
    ]
