# Generated by Django 3.2.5 on 2021-07-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergppoint',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
