# Generated by Django 3.2.5 on 2021-07-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_usergppoint_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.IntegerField(null=True),
        ),
    ]
