# Generated by Django 3.2.5 on 2021-08-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_useranswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ct_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
