# Generated by Django 3.2.5 on 2021-08-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_category_ct_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongp',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questions.answerer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='ans1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='ans2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
